{% set name = "pyclesperanto" %}
{% set version = "0.8.0" %}
{% set sha256 = "ea60de2b6a1920e25b25f19c69b74f3e6284f4da9bf8dfaa10ea8e5b439b3e1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [python_impl == 'pypy' and (aarch64 or ppc64le)]
  number: 0
  script:
    - CMAKE_GENERATOR="Ninja" {{ PYTHON }} -m pip install . -vv     # [linux or osx] 
    - {{ PYTHON }} -m pip install . -vv     # [win] 

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - cmake
    - ninja          # [linux or osx] 
    - {{ compiler('cxx') }}

  host:
    - pip
    - python
    - scikit-build-core
    - pybind11
    - numpy
    - khronos-opencl-icd-loader          # [win or osx] 
    - ocl-icd          # [linux]

  run:
    - python
    - numpy
    - toolz
    - matplotlib-base
    - khronos-opencl-icd-loader          # [win or osx] 
    - ocl-icd          # [linux]
    - libcxx         # [osx]
test:
  imports:
    - pyclesperanto
  requires:
    - pytest
    - pocl          # [linux or osx]
    - oclgrind          # [win]
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://pypi.org/project/pyclesperanto/
  doc_url: https://clesperanto.github.io/pyclesperanto/
  dev_url: https://github.com/clEsperanto/pyclesperanto/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: GPU-accelerated Image Processing library using OpenCL
  description: |
    pyclesperanto is the python package of clEsperanto - a multi-language framework for GPU-accelerated image processing. 
    clEsperanto uses OpenCL kernels extended with CLIJ custom syntax.
extra:
  recipe-maintainers:
    - StRigaud
    - haesleinhuepf
